### PR TITLE
Fixing Error

### PR DESCRIPTION
**Pull request by Sascha-T**

### CODE REVIEW

**Comment by Galaxtone** [comment]
Fixed issue with code.

**Comment by Sascha-T** [comment]
@Galaxtone you shouldve merged it

**Comment by Sascha-T** [comment]
instead of just recommiting

**Comment by Galaxtone** [comment]
I am sorry but I noticed the issue before your request.

**Comment by Galaxtone** [comment]
Also it looks like the cat has a beard on it

**Pull request closed without merging**
